# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bms_mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bms_mobile
	pod 'SwiftyJSON', '3.1.4'
	pod 'Charts', '3.0.3'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  target 'bms_mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
	  target.build_configurations.each do |config|
	    config.build_settings['SWIFT_VERSION'] = '3.0'
	  end
	end
end

target 'bms_mobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bms_mobile-tvOS

  target 'bms_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
